import type { Metadata } from "next";
import "./globals.css";
import { GlobalProvider } from "@/contexts/GlobalProvider";
import { UserProvider } from "@/contexts/UserProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <GlobalProvider>
          <UserProvider>{children}</UserProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
